# Generated by Django 5.0.7 on 2024-11-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='cover_pic',
            field=models.ImageField(blank=True, upload_to='cover_pics/'),
        ),
    ]
