# Generated by Django 5.0.7 on 2025-04-24 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_readingsession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingsession',
            old_name='session_date',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='readingsession',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reading_sessions', to='book.book'),
        ),
    ]
