# Generated by Django 5.0.7 on 2025-06-04 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_rename_session_date_readingsession_timestamp_and_more'),
        ('bookclubs', '0003_alter_bookclub_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readingprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='book_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookclubs.bookclub'),
        ),
        migrations.AlterUniqueTogether(
            name='readingprogress',
            unique_together={('user', 'book', 'book_club')},
        ),
    ]
