# Generated by Django 5.0.7 on 2025-06-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookclub',
            options={'verbose_name_plural': 'Book Clubs'},
        ),
    ]
